### ISSUE TITLE
mutrec-lib.R ? 

### ISSUE THREAD

**Issue by danchubb** [skandlab/MutSpot#1]
Hi,

I have started following your protocol and the following file is sourced in the first script. 

source('~/Gastric_Cancer/scripts/mutrec-lib.R')

Is this required and if so could you add it to the repository?

Thanks

**Comment by AmandaMilou** [comment]
Hello,

We are in the process of packaging the scripts into an user friendly R package for mutation hotspot detection. The first version will be uploaded within 1-2 weeks. Please check back soon.

**Comment by danchubb** [comment]
Hi,

That's great. Any more news on the [R] package release?

Thanks a lot

Dan

**Comment by AmandaMilou** [comment]
HI Dan,

Sorry for the delay. We aim to get it up by next week. Thank you for your
patience.

Amanda

**Comment by danchubb** [comment]
Great,

Looking forward to trying it on our dataset.

**Comment by AmandaMilou** [comment]
Hi Dan,

The package is now available. Please give it a try and let us know if you
encounter any issues.
