### ISSUE TITLE
Issue with MutSpot Package and R Version Compatibility

### ISSUE THREAD

**Issue by MichaelPudjihartono** [skandlab/MutSpot#15]
Hi,
Firstly, I want to express my gratitude for developing the MutSpot package.

I am trying to run some analysis using MutSpot, but did not find success because of problems with versioning.
I understand that MutSpot is tested for R version 3.2 to 3.6, 

However, R and all packages in CRAN has since been updated to the degree that many packages are not even available for these older R version.

The problem is that, even though my R version is compatible with MutSpot (v 3.5.3 in this case), the package still attempts to download the latest versions of these dependencies, which are incompatible with the older R version required by MutSpot.

For example, when I use R 3.5.3 to run MutSpot, 
I encounter problems that packages such as 'glmnet', 'poibin' and many others are not available anymore for R 3.5

I was wondering if there is any advice or workaround to address this compatibility issue?

Thank you so much!

**Comment by AmandaMilou** [comment]
Hi Michael,

Thank you for bringing up the compatibility issue. For now, could you modify the package installation code to install a specific version of the package that is compatible with R3.5?  For example, change install.packages("glmnet") to install_version ("glmnet", version="2.0-18"). We are working to update the package for compatibility with newer R versions.

**Comment by MichaelPudjihartono** [comment]
Thanks for your reply,

The problem with this approach would be that "install_version()" require devtools package which is not available anymore in R 3.5/3.6

In this case, would you advice on manually installing the old version of devtools (and all of its dependencies) manually?

It would be great if there is a docker container which contains all dependencies already installed

Thank you so much,
Michael

**Comment by MichaelPudjihartono** [comment]
UPDATE: I was able to make MutSpot work

It looks like installing the dependencies using conda is the way to go. As a result I was able to run MutSpot on R 3.6.3 (Which is not a problem right?)

**Comment by AmandaMilou** [comment]
Hi Michael, glad that it is working. Thanks for the feedback.
