### ISSUE TITLE
MutSpot doesn’t pass step 5.1

### ISSUE THREAD

**Issue by marialitovchenko** [skandlab/MutSpot#7]
Hello, 

I was excited to try MutSpot and I think that the idea behind it is great! However, while testing, I run into an error: MutSpot never passes step 5.1. I’ve waited for > 4h for it to finish on the test data from chr21 (on 4 cores with 100Gb RAM), but it never did, despite that in README it’s noted that MutSpot run on whole genome should take < 1 day on 2 cores.

Steps to reproduce the issue:
1) create chr21 MAF file:
`grep chr21 subset_snv_mutations_sid.MAF > subset_snv_mutations_sid_chr21.MAF`

2) Run MutSpot step by step with genomic_features_genome_default.txt and features folder located in the working directory: 
```
for (stepID in c(1,2,3.1,3.2,4.1,4.2,5.1,5.2,5.3,5.4,5.5,6,7)) {
  MutSpot(run.to = stepID, chromosome = "21", 
          snv.mutations = 'subset_snv_mutations_sid_chr21.MAF',
          genome.build = 'Ch37' cores = 4,  cutoff.nucleotide.new = 1, 
          genomic.features = ‘genomic_features_genome_default.txt’)
}
```

Last file created in results folder: continuous_features_selected_snv_url.txt

Could you please help me to resolve this issue?

**Comment by AmandaMilou** [comment]
Hello,
Thanks for your interest in the package. If you want to run MutSpot on chromosome 21 only, you should also pass in a bed file with the genomic region of interest using the "region.of.interest" parameter. Else the model will attempt to fit a model on the whole genome although only mutations on chromosome 21 is given, and that may cause model convergence issues.

**Comment by marialitovchenko** [comment]
Hello Amanda,

Thank you for your reply! I've created a bed called `roi_chr21.bed` file with the following line:
`chr21    1    48059893`

and modified the code to:
```
for (stepID in c(1,2,3.1,3.2,4.1,4.2,5.1,5.2,5.3,5.4,5.5,6,7)) {
  MutSpot(run.to = stepID, chromosome = "21", region.of.interest = 'roi_chr21.bed',
          snv.mutations = 'subset_snv_mutations_sid_chr21.MAF',
          genome.build = 'Ch37' cores = 4,  cutoff.nucleotide.new = 1, 
          genomic.features = ‘genomic_features_genome_default.txt’)
}
```
However, MutSpot is still stuck on step 5.1.

**Comment by changmmm** [comment]
Hi,

We've reproduced your subset_snv_mutations_sid_chr21.MAF file and ran MutSpot in the same way as you first did it. We were able to pass step 5.1 till the end with a 64Gb machine on 8 cores in around 10 minutes. Would you be able to provide us with a log of what MutSpot has printed till the point you think it is stuck? Thanks!

**Comment by marialitovchenko** [comment]
Hi,

I've tried to run MutSpot again with 8 cores instead of 4, 64Gb RAM and it didn't finished within 4h unfortunately and then the job was killed. Please find pdf with MutSpot output attached. I'm sorry it's in a such format, but I'm working inside a secure environment and it's very difficult to export files from it. Interestingly, MutSpot didn't produce any error message any time I run it.
[MutSpot_Output.pdf](https://github.com/skandlab/MutSpot/files/5962502/MutSpot_Output.pdf)
[MutSpot_Output.pdf](https://github.com/skandlab/MutSpot/files/5962504/MutSpot_Output.pdf)



Thank you very much for helping me!

**Comment by AmandaMilou** [comment]
Hello,

Unfortunately we are unable to replicate the issue on our end. Normally when the software doesn't finish running, we would suspect a memory issue. However, the memory that you allocated should be more than enough. Perhaps you can try on another computer system? For just chromosome 21, the software should be able to run on a regular desktop/laptop (16Gb) using 1 core.
