### ISSUE TITLE
Splitting 5.1 by chromosome

### ISSUE THREAD

**Issue by danchubb** [skandlab/MutSpot#8]
Hi, 

Since the hg38 update I am trying to get mutspot working on my data again. Some bits of the workflow are very slow, especially 5.1 but I think by splitting by chromosome I have managed to speed it up. Can I just check that by doing this I am not breaking anything? 

I run everything up to 5.1 on the full dataset. Once I reach 5.1 I set off a run for each chromosome using all the same parameters and  the chromosome=n argument. This produces a mutCovariate_chrn.RDS for every chromosome. I then copy all of these in to the same results directory and continue from 5.2 without the chromosome argument. As far as i can tell from the code, this replicates the per-chromosome loop in 5.1 but allows me to spread it across several HPC submissions in place of trying to get a large allocation of cores/memory which is difficult. 

Running the test you provide gives me reasonable looking results, I just want to make sure I'm not missing anything. 

![image](https://user-images.githubusercontent.com/8969482/116699103-1ae41380-a9bd-11eb-9d93-72aa170732a4.png)

Thanks for the help - I'm looking forward to getting some interesting results!

Dan

**Comment by AmandaMilou** [comment]
Hi Dan,

Sorry for the late reply. What you are doing is absolutely fine.

**Comment by danchubb** [comment]
Awesome. Thanks for the assurance. Now I know that's not the problem, I'm getting some other error with the indel calculations - I'll submit that as another issue though :)

Thanks again,

Dan
